import React from "react";
import {
  Palette,
  Share2,
  Printer,
  Package,
  Megaphone,
  Compass,
  Lightbulb,
  Clock,
  MessageCircle,
  MessageSquare,
  PenTool,
  Brush,
  Camera,
  Film,
  BookOpen,
  Award,
  CheckCircle,
  CheckCircle2,
  Check,
  Star,
  Search,
  Send,
  User,
  Phone,
  Mail,
  MapPin,
  Sparkles,
  ArrowRight,
  ArrowLeft,
  Calendar,
  Layers,
  Shield,
  Target,
  Smartphone,
  Laptop,
  FolderArchive,
  GraduationCap,
  Heart,
  HelpCircle,
  Image,
  ZoomIn,
  ZoomOut,
  X,
  Menu,
  Sun,
  Moon,
  Globe,
  Share,
  FileText,
  Bookmark,
  Hash,
  AlertTriangle,
  RefreshCw,
  Home,
  CheckSquare,
  List,
  Eye,
  Sliders,
  Filter,
  Users,
  Briefcase,
  Store,
  Folder,
} from "lucide-react";

/**
 * Global Mapping dictionary from icon names/keys to Lucide components
 */
const ICON_MAP = {
  // Common / Design
  palette: Palette,
  category: Palette,
  draw: PenTool,
  pen_tool: PenTool,
  brush: Brush,
  design_services: PenTool,
  photo_camera: Camera,
  camera: Camera,
  movie: Film,
  film: Film,
  auto_stories: BookOpen,
  book_open: BookOpen,
  print: Printer,
  printer: Printer,
  share: Share2,
  share2: Share2,
  social: Share2,
  inventory_2: Package,
  package: Package,
  packaging: Package,
  campaign: Megaphone,
  megaphone: Megaphone,
  ads: Megaphone,
  insights: Compass,
  compass: Compass,
  visual_consultations: Compass,
  lightbulb: Lightbulb,
  ideas: Lightbulb,
  precision: Target,
  target: Target,
  deadline: Clock,
  schedule: Clock,
  clock: Clock,
  timer: Clock,
  communication: MessageCircle,
  chat: MessageCircle,
  forum: MessageSquare,
  message: MessageSquare,
  award: Award,
  workspace_premium: Award,
  verified: CheckCircle2,
  check_circle: CheckCircle,
  check: Check,
  star: Star,
  search: Search,
  send: Send,
  user: User,
  call: Phone,
  phone: Phone,
  email: Mail,
  mail: Mail,
  location_on: MapPin,
  map_pin: MapPin,
  sparkles: Sparkles,
  auto_awesome: Sparkles,
  arrow_forward: ArrowRight,
  arrow_right: ArrowRight,
  arrow_back: ArrowLeft,
  arrow_left: ArrowLeft,
  calendar_today: Calendar,
  calendar: Calendar,
  layers: Layers,
  shield: Shield,
  smartphone: Smartphone,
  devices: Smartphone,
  laptop: Laptop,
  folder_zip: FolderArchive,
  folder_archive: FolderArchive,
  folder: Folder,
  school: GraduationCap,
  graduation_cap: GraduationCap,
  heart: Heart,
  image: Image,
  zoom_in: ZoomIn,
  zoom_out: ZoomOut,
  close: X,
  menu: Menu,
  sun: Sun,
  moon: Moon,
  globe: Globe,
  label: Bookmark,
  tag: Hash,
  alert_triangle: AlertTriangle,
  warning_amber: AlertTriangle,
  refresh: RefreshCw,
  autorenew: RefreshCw,
  home: Home,
  list: List,
  format_list_bulleted: List,
  eye: Eye,
  filter: Filter,
  users: Users,
  groups: Users,
  briefcase: Briefcase,
  store: Store,
  storefront: Store,
  handshake: Users,
  psychology: Lightbulb,
  rocket_launch: Sparkles,
  thumb_up: Award,
};

export const LucideIcon = ({
  name,
  size = 20,
  strokeWidth = 1.75,
  className = "",
  fallback = Palette,
  ...props
}) => {
  if (!name) return null;

  const normalized = typeof name === "string" ? name.toLowerCase().trim() : "";
  const Component = ICON_MAP[normalized] || fallback;

  return (
    <Component
      size={size}
      strokeWidth={strokeWidth}
      className={`inline-block transition-transform duration-300 ${className}`}
      aria-hidden="true"
      {...props}
    />
  );
};
